name: 'Kt Lint PR Review'
description: 'Run Ktlint in your repo, collect results and post PR reviews if there are any ktlint comments in your changed files of the PR'

inputs:
  github_token:
    description: 'Github token is required to fetch changes of the PR and post comments'
    required: true

  event_file_path:
    description: 'Event file path contains info about this PR, so the Github REST APIs need that info which is why this is required too'
    required: true

  ktlint_version:
    description: 'specify ktlint version if you need speical version, default version will be 0.48.0'
    default: 0.48.0
    required: false

  log_level:
    description: use either of 'trace', 'debug', 'info', 'warn', 'error', or 'none', default is 'info'
    default: 'info'
    required: false

  experimental:
    description: enable or disable experimental rules
    default: false
    required: false

  configFilePath:
    description: path to .editorConfig file. by default it will look for it in the root of the repo
    default: '/'
    required: false

runs:
  using: 'composite'
  steps: 
    - name: Starting Kt Lint Flow
      run: echo 'Start Kt Lint Flow....'
      shell: bash
    
    - name: printing from input....
      run: echo ${{ inputs.event_file_path }}
      shell: bash

    - name: Downloading KtLint
      run: |
        curl -sSLO https://github.com/pinterest/ktlint/releases/download/${{inputs.ktlint_version}}/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      shell: bash

    # - name: run ktlint scan
    #   run: |
    #     ktlint --log-level=${{inputs.log_level}} --reporter=json,output=ktlint-report.json
    #   continue-on-error: true
    #   shell: bash

    - run: kotlin ${GITHUB_ACTION_PATH}/src/github-pr-reviews.main.kts ${{ inputs.event_file_path }} ${{ inputs.github_token }} ${{ inputs.log_level }} ${{ inputs.experimental }} ${{ inputs.configFilePath }}
      continue-on-error: true
      shell: bash
