name: 'Kt Lint PR Review'
description: 'Run Ktlint in your repo, collect results and post PR reviews if there are any ktlint comments in your changed files of the PR'

inputs:
  github_token:
    description: 'Github token is required to fetch changes of the PR and post comments'
    required: true

  event_file_path:
    description: 'Event file path contains info about this PR, so the Github REST APIs need that info which is why this is required too'
    required: true

runs:
  using: 'composite'
  steps: 
    - name: Starting Kt Lint Flow
      run: echo 'Start Kt Lint Flow....'
      shell: bash
    
    - name: printing from input....
      run: echo ${{ inputs.event_file_path }}
      shell: bash

    - name: Downloading KtLint
      run: |
        curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.44.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      shell: bash

    - name: run ktlint scan
      run: |
        ktlint --reporter=json,output=ktlint-report.json
      continue-on-error: true
      shell: bash

    - run: |
        kotlin src/github-pr-reviews.main.kts ${{ inputs.event_file_path }} ${{ inputs.github_token }}
      shell: bash
      