name: 'Kt Lint PR Review'
description: 'Run Ktlint in your repo, collect results and post PR reviews if there are any ktlint comments in your changed files of the PR'

inputs:
  github_token:
    description: 'Github token is required to fetch changes of the PR and post comments'
    required: true

  event_file_path:
    description: 'Event file path contains info about this PR, so the Github REST APIs need that info which is why this is required too'
    required: true

  ktlint_version:
    description: 'ktlint version, if not specified, 0.44.0 will be used as default'
    required: false

# runs:
#   using: 'docker'
#   image: 'Dockerfile'
#   args:
#     - ${{ inputs.github_token }}
#     - ${{ inputs.even_file_path }}
#     - ${{ inputs.ktlint_version }}

runs:
  using: 'composite'
  steps: 
    - name: Starting Kt Lint Flow
      run: echo 'Start Kt Lint Flow....'
      shell: bash
    
    - name: printing from input....
      run: echo ${{ inputs.event_file_path }}

    - run: kotlin ./.github/scripts/ktlint/github-pr-reviews.main.kts ${{ inputs.event_file_path }} ${{ inputs.github_token }}
      shell: bash

# runs:
#   using: 'node16'
#   main: 'index.js'