name: ktlint pr review

on:
  workflow_call:

jobs:
  scan_with_ktlint_and_post_results_as_reviews:
    name: KtLint Scan and Reviews
    runs-on: ubuntu-latest

    steps:
      - name: Just dummy starting log comment
        echo: 'starting run-ktlint.yml'

      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Downloading KtLint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.44.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/

      - name: run ktlint scan
        run: |
          ktlint --reporter=json,output=ktlint-report.json
        continue-on-error: true

      - name: Fetch PR changes and post review from scan
        run:
          kotlin .github/scripts/ktlint/github-pr-reviews.main.kts ${{ github.event_path }} ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true